# backend: הגדרות חיבור ל-GitHub דרך Netlify
backend:
  name: git-gateway # הדרך המומלצת לחיבור ל-GitHub כשמשתמשים ב-Netlify
  branch: main     # הענף שבו אתה רוצה ש-Decap CMS יערוך (לרוב main או master)

# media_folder: איפה לשמור את קבצי המדיה (תמונות, קבצים)
# הנתיב הזה הוא יחסי לשורש המאגר שלך. ודא שהוא נכון עבור Hugo!
media_folder: "static/uploads" # Hugo מפרסם את מה שבתוך static/ לשורש האתר

# public_folder: הנתיב הציבורי לקבצי המדיה באתר
# הנתיב הזה יחסי לשורש האתר המפורסם שלך.
public_folder: "/uploads" # למשל, תמונה שהועלתה תהיה נגישה ב-your-site.com/uploads/image.jpg

# collections: הגדרת סוגי התוכן ש-Decap CMS ינהל
collections:
  - name: "posts" # שם פנימי ל-collection
    label: "פוסטים בבלוג" # השם שיופיע בממשק הניהול
    folder: "content/posts" # הנתיב לתיקייה שבה נמצאים קבצי הפוסטים (יחסי לשורש המאגר)
    create: true # האם ניתן ליצור פוסטים חדשים
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # תבנית לשם הקובץ של פוסט חדש
    fields: # השדות שיופיעו בעורך עבור כל פוסט
      - {label: "כותרת", name: "title", widget: "string"}
      - {label: "תאריך פרסום", name: "date", widget: "datetime"}
      - {label: "תמונה ראשית", name: "image", widget: "image", required: false}
      - {label: "תיאור קצר", name: "description", widget: "string", required: false}
      - {label: "תוכן הפוסט", name: "body", widget: "markdown"}
      - {label: "קטגוריות", name: "categories", widget: "list", required: false}
      - {label: "תגיות", name: "tags", widget: "list", required: false}

  - name: "pages"
    label: "עמודים"
    folder: "content" # עמודים בודדים כמו "אודות", "צור קשר" נמצאים לעיתים קרובות ישירות ב-content/
    filter: {field: "layout", pattern: "page"} # אופציונלי: אם אתה משתמש בשדה 'layout' כדי להבדיל בין סוגי עמודים
    create: true
    fields:
      - {label: "כותרת", name: "title", widget: "string"}
      - {label: "תוכן העמוד", name: "body", widget: "markdown"}
      - {label: "תבנית עמוד", name: "layout", widget: "hidden", default: "page"} # שדה נסתר אם אתה משתמש ב-layout: page
      - {label: "Permalink", name: "permalink", widget: "string", required: false} # אם אתה מגדיר נתיבים מותאמים אישית ב-front matter

  # הוסף כאן collections נוספים לפי הצורך, למשל:
  # - name: "authors"
  #   label: "מחברים"
  #   folder: "data/authors" # אם אתה שומר נתוני מחברים בקבצי YAML/JSON בתיקיית data
  #   create: true
  #   fields:
  #     - {label: "שם", name: "name", widget: "string"}
  #     - {label: "ביוגרפיה", name: "bio", widget: "text"}
